(cl:defpackage outdoor_gcs-srv
  (:use )
  (:export
   "CONTROLPARAMETER"
   "<CONTROLPARAMETER-REQUEST>"
   "CONTROLPARAMETER-REQUEST"
   "<CONTROLPARAMETER-RESPONSE>"
   "CONTROLPARAMETER-RESPONSE"
   "GENERALINFO"
   "<GENERALINFO-REQUEST>"
   "GENERALINFO-REQUEST"
   "<GENERALINFO-RESPONSE>"
   "GENERALINFO-RESPONSE"
   "MULTIPAYLOADACTION"
   "<MULTIPAYLOADACTION-REQUEST>"
   "MULTIPAYLOADACTION-REQUEST"
   "<MULTIPAYLOADACTION-RESPONSE>"
   "MULTIPAYLOADACTION-RESPONSE"
   "SINGLEPAYLOADACTION"
   "<SINGLEPAYLOADACTION-REQUEST>"
   "SINGLEPAYLOADACTION-REQUEST"
   "<SINGLEPAYLOADACTION-RESPONSE>"
   "SINGLEPAYLOADACTION-RESPONSE"
  ))

