// Generated by gencpp from file outdoor_gcs/ControlParameter.msg
// DO NOT EDIT!


#ifndef OUTDOOR_GCS_MESSAGE_CONTROLPARAMETER_H
#define OUTDOOR_GCS_MESSAGE_CONTROLPARAMETER_H

#include <ros/service_traits.h>


#include <outdoor_gcs/ControlParameterRequest.h>
#include <outdoor_gcs/ControlParameterResponse.h>


namespace outdoor_gcs
{

struct ControlParameter
{

typedef ControlParameterRequest Request;
typedef ControlParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlParameter
} // namespace outdoor_gcs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::outdoor_gcs::ControlParameter > {
  static const char* value()
  {
    return "6564e4eb6ec261394b295cdd4e73b53a";
  }

  static const char* value(const ::outdoor_gcs::ControlParameter&) { return value(); }
};

template<>
struct DataType< ::outdoor_gcs::ControlParameter > {
  static const char* value()
  {
    return "outdoor_gcs/ControlParameter";
  }

  static const char* value(const ::outdoor_gcs::ControlParameter&) { return value(); }
};


// service_traits::MD5Sum< ::outdoor_gcs::ControlParameterRequest> should match
// service_traits::MD5Sum< ::outdoor_gcs::ControlParameter >
template<>
struct MD5Sum< ::outdoor_gcs::ControlParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::outdoor_gcs::ControlParameter >::value();
  }
  static const char* value(const ::outdoor_gcs::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::outdoor_gcs::ControlParameterRequest> should match
// service_traits::DataType< ::outdoor_gcs::ControlParameter >
template<>
struct DataType< ::outdoor_gcs::ControlParameterRequest>
{
  static const char* value()
  {
    return DataType< ::outdoor_gcs::ControlParameter >::value();
  }
  static const char* value(const ::outdoor_gcs::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::outdoor_gcs::ControlParameterResponse> should match
// service_traits::MD5Sum< ::outdoor_gcs::ControlParameter >
template<>
struct MD5Sum< ::outdoor_gcs::ControlParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::outdoor_gcs::ControlParameter >::value();
  }
  static const char* value(const ::outdoor_gcs::ControlParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::outdoor_gcs::ControlParameterResponse> should match
// service_traits::DataType< ::outdoor_gcs::ControlParameter >
template<>
struct DataType< ::outdoor_gcs::ControlParameterResponse>
{
  static const char* value()
  {
    return DataType< ::outdoor_gcs::ControlParameter >::value();
  }
  static const char* value(const ::outdoor_gcs::ControlParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUTDOOR_GCS_MESSAGE_CONTROLPARAMETER_H
