// Generated by gencpp from file outdoor_gcs/GeneralInfo.msg
// DO NOT EDIT!


#ifndef OUTDOOR_GCS_MESSAGE_GENERALINFO_H
#define OUTDOOR_GCS_MESSAGE_GENERALINFO_H

#include <ros/service_traits.h>


#include <outdoor_gcs/GeneralInfoRequest.h>
#include <outdoor_gcs/GeneralInfoResponse.h>


namespace outdoor_gcs
{

struct GeneralInfo
{

typedef GeneralInfoRequest Request;
typedef GeneralInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneralInfo
} // namespace outdoor_gcs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::outdoor_gcs::GeneralInfo > {
  static const char* value()
  {
    return "f5411d5ea2241dbc1c5aa4c2c6403d8d";
  }

  static const char* value(const ::outdoor_gcs::GeneralInfo&) { return value(); }
};

template<>
struct DataType< ::outdoor_gcs::GeneralInfo > {
  static const char* value()
  {
    return "outdoor_gcs/GeneralInfo";
  }

  static const char* value(const ::outdoor_gcs::GeneralInfo&) { return value(); }
};


// service_traits::MD5Sum< ::outdoor_gcs::GeneralInfoRequest> should match
// service_traits::MD5Sum< ::outdoor_gcs::GeneralInfo >
template<>
struct MD5Sum< ::outdoor_gcs::GeneralInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::outdoor_gcs::GeneralInfo >::value();
  }
  static const char* value(const ::outdoor_gcs::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::outdoor_gcs::GeneralInfoRequest> should match
// service_traits::DataType< ::outdoor_gcs::GeneralInfo >
template<>
struct DataType< ::outdoor_gcs::GeneralInfoRequest>
{
  static const char* value()
  {
    return DataType< ::outdoor_gcs::GeneralInfo >::value();
  }
  static const char* value(const ::outdoor_gcs::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::outdoor_gcs::GeneralInfoResponse> should match
// service_traits::MD5Sum< ::outdoor_gcs::GeneralInfo >
template<>
struct MD5Sum< ::outdoor_gcs::GeneralInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::outdoor_gcs::GeneralInfo >::value();
  }
  static const char* value(const ::outdoor_gcs::GeneralInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::outdoor_gcs::GeneralInfoResponse> should match
// service_traits::DataType< ::outdoor_gcs::GeneralInfo >
template<>
struct DataType< ::outdoor_gcs::GeneralInfoResponse>
{
  static const char* value()
  {
    return DataType< ::outdoor_gcs::GeneralInfo >::value();
  }
  static const char* value(const ::outdoor_gcs::GeneralInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUTDOOR_GCS_MESSAGE_GENERALINFO_H
